### PR TITLE
[WIP] Script for tracking with BayesianTracker 

### PR DESCRIPTION
**Pull request by AbigailMcGovern**
I have written an initial script for tracking with BayesianTracker. Whilst this technically works, the tracking configuration __*definitely*__ needs to be refined. The configuration file is called `platelet_config.json`. It is based on the example provided with BayesianTracker (called `cell_config.json`). I have a feeling that the hypothesis parameters are poorly chosen, as the ILP optimisation is taking a really long time (it doesn't in the colab notebook provided in the `track` README) and the comments in the code note that if the hypotheses are chosen poorly this part of the process can take (and I quote) `*FOREVER*`. The only changes I have made so far is to remove the `"P_branch"` hypothesis so that the platelets don't start magically 'dividing'. After some __intensive__ reading and code diving (which included consultation of a very scary C++ tutorial 😫 😂 - to be fair this was actually sort of fun) I have compiled some notes about the meaning of some, but not yet all, of the fields in the configuration file.   

__Changes:__
- addition of tracking script `track_tracking.py`. This script has the same CLI as `view_tracks.py`
- alteration to `view_tracks.py` to facilitate viewing of the newly generated tracks in the new script
- addition of `track_notes.md` which summarises my current knowledge of BayesianTracker and it's configuration file
- alteration of `parser.py` to 

@jni I have attached a G-drive link showing a video of the un-configured tracking [here](https://drive.google.com/file/d/12fAK0n1Qf-bub07uPUG0oPXmtvV640Q_/view?usp=sharing) if you are interested in seeing how this looks (screenshot from this video below). I will say that upon closer inspection, it seems to track more of the platelets and loose fewer tracks than `trackpy`. I don't think it's quite as bad as it looks in the picture. 

201009_btrack-attempt-0-ss

### CODE REVIEW

**Comment by jni** [comment]
@quantumjot Ok I think this ping will work now that this repo is public! You can see me embarrassing myself just above. 😂 

Anyway, hello @quantumjot! 😊 So as you can see above, @AbigailMcGovern has been trying out btrack for some of our own data, and has made rather heroic efforts doing parameter tuning for our data. But btrack takes a while and we don't really have ground truth for this data, so it's a rather arduous process, and we're wondering if you have any tips for parameter tuning and accuracy evaluation. Also, there doesn't seem to be much documentation around btrack (apologies if we've missed it), so we've been flying a bit in the dark — tracking is new to both of us. Perhaps with your help we can start to contribute to btrack documentation, while you help us get better results? 😬 😊 

Thank you!

**Comment by quantumjot** [comment]
Hello again! 

First off, it's great to see `btrack` (and the `Tracks` layer) in use on something other than our own data! I built it for our group, so I'm totally amazed at what you've managed to get so far with your data (kudos to @AbigailMcGovern!), and now I know that at least two people have read the source code...

There's no getting away from needing *some* GT data, especially if you want to do hyperparameter tuning. This is a complex problem in `btrack` because the tracklet generation and optimization steps have a non-trivial interaction. For example, in some cases, having fragmented tracklets shorter (i.e. worse) and then letting the optimizer do its work, actually yields better results. In my experience, it's very problem specific (aka quirky). 

A general observation is that, if the optimizer is struggling to find a solution in less than a minute, the problem is probably not well posed, and the result will not be good. To help with (automating) tuning, you can by pass the following option to timeout the optimizer after say, 60 seconds:
```python
tracker.optimize(options={'tm_lim': int(6e4)})
```
I'm happy to help you troubleshoot this!

The documentation is sparse, but there is some additional info (see https://github.com/quantumjot/BayesianTracker/issues/12#issuecomment-723839263). It's the number one request from users, but has been tough to convince people to help add the documentation. I have very limited time, so I would welcome any input.

**Comment by quantumjot** [comment]
Oh, and I just saw #15 - nice!

One thing that helps with automating parameter scans is that you can use `tracker.configure(config_dict)` rather than `tracker.configure_from_file()` where config_dict is just the contents of the json file as a dictionary. You can programmatically adjust the parameters without needing to write out the file...

**Comment by AbigailMcGovern** [comment]
Hi @quantumjot,

Thanks for getting back to us so quickly and for the feedback! This is already very helpful! I have certainly been on quite the adventure in attempts to refine the tracking (and exploring at least a chunk of the source code) 😄. 

> There's no getting away from needing _some_ GT data, especially if you want to do hyperparameter tuning. 

@jni and I have gradually realised this (very much the hard way, at least on my part). As you have probably seen in #15, we are aiming to tune parameters with the hyperparameter optimisation package `optuna`. We initially attempted to tune the parameters using a proofreading interface, which I had previously developed for assessing track accuracy. Unfortunately this seemed to be a fairly inefficient way to generate costs (as this requires a lot of user input and provides a rather blunt measure of accuracy). The next step will likely be to move towards optimisation based on difference from (incomplete) GT data (specifics TBD).

> For example, in some cases, having fragmented tracklets (i.e. worse) and then letting the optimizer do its work, actually yields better results. In my experience, it's very problem specific (aka quirky).

That is very useful to know, thanks. I'll definitely keep this in mind when choosing parameter ranges.

> A general observation is that, if the optimizer is struggling to find a solution in less than a minute, the problem is probably not well posed, and the result will not be good. To help with (automating) tuning, you can by pass the following option to timeout the optimizer after say, 60 seconds:

Good to know. Hmm... this is quite a revelation and should increase our search efficiency substantially. In most instances, tracking has taken *much* longer than one minute, with the best options so far taking 10-15 min (with a large portion of that time used by the solver). Only when there were almost an order of magnitude fewer objects did the times drop closer to a minute (although this is probably still longer than recommended).


> To help with (automating) tuning, you can by pass the following option to timeout the optimizer after say, 60 seconds:

Great! Thanks 😃. This is a great deal simpler than my method 😂 


> You can programmatically adjust the parameters without needing to write out the file...

Awesome! That should clean things up quite nicely.

**Comment by quantumjot** [comment]
> with a large portion of that time used by the solver 

I should also point out that there are quite a few hidden troubleshooting features in `btrack`, but the tracking log itself is super useful. If you could share that, that would really help get a handle on what is actually happening during the tracking.

**Pull request merged**
